### ISSUE TITLE
Add a notification to show next scheduled alarm

### ISSUE THREAD

**Issue by yuriykulikov** [yuriykulikov/AlarmClock#14]
This should be configurable in settings.

Think about optional additional buttons: edit, skip occurence, etc.

**Comment by gerhardol** [comment]
The notification time should be configurable. I would use 8h so I can cancel when going to bed, other could use 1h. 
Action when clicking notification ago of be to edit the alarm. 
The buttons could be skip and snooze (to postpone the alarm time for this occurrence only). 

Related to this, I would like to be able to skip next alarm from the app. Before notification appears, for instance for work alarms. 

I may look into this myself. If the intentions exist, this could be simple.

**Comment by yuriykulikov** [comment]
Hi,
Sure you can :-) I can give you some tips regarding this change. First, you
will need a new state in the state machine (skipping Today). Then a method
in the alarm core to get into that state. Then the simplest way would be to
add this action to the context menu in the list. After that we need to
display this state in the list. Another context menu to "unskip" the alarm.

After all this is done, and we have an upcoming alarm notification, we can
also integrate it into the notification.

Cheers

**Comment by yuriykulikov** [comment]
Done!

**Comment by gerhardol** [comment]
Thanks!
