### ISSUE TITLE
Gradle build system

### ISSUE THREAD

**Issue by krt16s** [yuriykulikov/AlarmClock#220]
It seems like you only pushed the actual app folder and not the root of the project (which should contain ca build.gradle as well as a settings file declaring what androidutils is. Ideally you would set the latter oncee up as a git submodule, so one can easily checkout a complete working build enviroment.

**Comment by yuriykulikov** [comment]
Yes you are right. I had exactly the same idea with submodules. Gonna push now.

**Comment by yuriykulikov** [comment]
Here goes https://github.com/yuriykulikov/AlarmClockAndroidStudio

**Comment by yuriykulikov** [comment]
Let me know if the issue is solved and I will close it

**Comment by krt16s** [comment]
I wouldn't have split it into three repos, but only one main repo and one for the utils, but it works. Thanks.

**Comment by yuriykulikov** [comment]
Hi,
I am using utils in other projects and eventually it will become a gradle
dependency.
