### ISSUE TITLE
Failed to build with error ':androidUtils' could not be found in root project 'AlarmClock'

### ISSUE THREAD

**Issue by tianyin** [yuriykulikov/AlarmClock#224]
Hello, 

First of all, thanks for the great app. I wanna build the app in the git repo. So I cloned the master, and load into Android Studio. 

However, when I build the project, I encountered the following error

``> Project with path ':androidUtils' could not be found in root project 'AlarmClock'.``

which comes from the definition
``` 
dependencies {
    compile project(':androidUtils')
    ...
```
Could you point me how to build the app? Thank you very much!

**Comment by yuriykulikov** [comment]
Hi!
You have to clone this project: https://github.com/yuriykulikov/AlarmClockAndroidStudio and all its submodules. You can than open it as an AndroidStudio project. For now AndroidUtils are used a submodule but in future they are likely to be imported as a jar dependency.
