### ISSUE TITLE
Where is the androidUtils module?

### ISSUE THREAD

**Issue by ChenQingZhen** [yuriykulikov/AlarmClock#225]
Where is the androidUtils module?

**Comment by yuriykulikov** [comment]
Here: https://github.com/yuriykulikov/AndroidUtils

:-) Have fun!  You may also check https://github.com/yuriykulikov/AlarmClockAndroidStudio although now I see that I have checked in everything and you actually need only 2 gradle files.

**Comment by yuriykulikov** [comment]
Module was integrated.
