### ISSUE TITLE
[feature-request] Off option for 'fade-in duration'

### ISSUE THREAD

**Issue by revuwa** [yuriykulikov/AlarmClock#226]
First of all thanks a lot for your enthusiasm and sharing such a neat and useful app to the community!

I'm on AlarmClock v2.9.01 on my Samsung i9100 @ AOSP 4.2.2 and wanted to disable the fade-in feature, but I can't find an option for that.

I thought it would be cool, if you could add an 'Off' option inside the Settings -> 'Fade-in duration' point, (as it's the case under the 'Pre-alarm duration' point, already).

Thank in advance for any help or support.

**Comment by revuwa** [comment]
Hope you'll consider to add this little feature sometime in the future.
Thanks again for that great app!

**Comment by yuriykulikov** [comment]
Implemented by patheticcockroach in 390ff6bb4d7ae5b75fde63b7b059d6e410cdc15e
