### ISSUE TITLE
[bug?] Edit alarm doesn't work

### ISSUE THREAD

**Issue by revuwa** [yuriykulikov/AlarmClock#227]
I'm on AlarmClock v2.9.01 on my Samsung i9100 @ AOSP 4.2.2.

After opening the app I saw two already existing alarms. I long pressed on one of them and selected 'Edit alarm', but nothing happens. The same on the other alarm and on self created alarms, too.
The other both points ('Turn alarm on/off' and 'Delete alarm') are working as expected.

Because there is the 'encircled triangle-sign' on the right side of each alarm, which let me edit the alarm(s), this is not a big deal. But I thought you should know that.

**Comment by yuriykulikov** [comment]
Hi! Thanks a lot for the report:-) The issue was fixed with this commit: 94b66b235e47460722f4ec87f39a4e92fb614c27 . Please update from Play Market.
