### ISSUE TITLE
Missing tag 2.9.04

### ISSUE THREAD

**Issue by Primokorn** [yuriykulikov/AlarmClock#230]
Hi,
The Play Store shows up v2.9.04 but I don't see it here :https://github.com/yuriykulikov/AlarmClock/tags/

Thank you.

**Comment by yuriykulikov** [comment]
Hi!
I have pushed the tags:-)

**Comment by Primokorn** [comment]
Thanks :)
We are stuck at version 2.9.01 on F-Droid. One moderator of the their said that the repo that holds all the source is this one: https://github.com/yuriykulikov/AlarmClockAndroidStudio
But I don't see any tags there.

Could you solve the problem or come on [F-Droid](https://f-droid.org/forums/topic/simple-alarm-clock/)?
Keep it up!

**Comment by yuriykulikov** [comment]
Oh I see.
Ok I am gonna try to push there as well. But I have to get to my desktop PC.

**Comment by Primokorn** [comment]
Great, thanks. Please let me know when it's done.

**Comment by revuwa** [comment]
Thanks for looking into this.

I would love to see >= 2.9.05 on F-Droid, too.
Still crossing my fingers for that...
