### ISSUE TITLE
Alarm would not fired if app force close from recent app list

### ISSUE THREAD

**Issue by ruhul015** [yuriykulikov/AlarmClock#231]
What is the solution?

**Comment by yuriykulikov** [comment]
Hi!
There is no proper solution for this besides installing proper firmware on your device.

The behaviour you are experiencing is cause by an incorrect implementation of the recent apps list on your device. Reference devices with Android AOSP do not remove RTC alams of the applications closed by the recents app.

The only possible workaround I can imagine is to subscribe to some event which happens periodically and quite often and to restart the application then.
