### ISSUE TITLE
Dialog disappears on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [yuriykulikov/AlarmClock#232]
When I perform these sequences of events, the dialog on screen disappears:

1. Click on ...
2. Click on Settings
3. Click on Alarm Volume
4. Orientation Change

The dialog disappears unlike the dialogs associated with other preferences in the same list

**Comment by yuriykulikov** [comment]
Hi,
I think the real issue here is that settings activity is not locked to the
portrait mode. I will look into that. Thank you for submitting this.
