### ISSUE TITLE
Vulnerability in 2.9.01 as per F-Droid

### ISSUE THREAD

**Issue by SkyWheel** [yuriykulikov/AlarmClock#290]
Privet Yura,
I have been using your great app as a main alarmclock for many years. Unfortunately, F-Droid didn't update the app since 2.9.01. And now F-Droid even recommends to uninstall the app due to known vulnerabilities and disabled algorithm. Notsure why they did not uodate their build to the latest version. Do you have any idea on the issue?
As for now, I'm still using airgapped ancient lenovo device with 4.2.1 Android mainly because of your app. At the same time my main phone is latest pixel xl with android 8, but due to the F-Droid warning I'm not risking to install your app.
It would be really beneficial if you could upload .apk builds here as well.
Thank you for the app!

**Comment by yuriykulikov** [comment]
Hi,
This is very strange. Which kind of vulnerability this is? I do not have
access to any user data, internet or any other potentially dangerous
resources. I do not use any native code or algorithms. Does the f-droid say
which vulnerability this is?

**Comment by SkyWheel** [comment]
I don't have any info on the vulnerability, and didn't check F-Droid forums yet. But I was going to create a thread on the forum to clarify that stuff. 
As soon as I create the thread I'll leave a link for it here.

**Comment by SkyWheel** [comment]
As promised, here is the F-Droid forum [topic](https://forum.f-droid.org/t/simple-alarm-clock-disappeared-from-f-droid-repo/1317?u=skywheel)

**Comment by SkyWheel** [comment]
Hi Yuriy,
Is the app abandoned?

**Comment by yuriykulikov** [comment]
Hi,
No it is not abandoned, but at the moment I do not get much time to develop
it.
Best wishes,
Yuriy

**Comment by yuriykulikov** [comment]
So I guess this is not relevant anymore
