### ISSUE TITLE
Snooze stopped working

### ISSUE THREAD

**Issue by ThomasRitter75** [yuriykulikov/AlarmClock#295]
Recently (a week?) Snooze/set later time stopped working for me. I set a new time for a later alarm, but the alarm does not sound. 

OS: LineageOS 14.1-20180801-NIGHTLY-athene on Moto G4.

**Comment by yuriykulikov** [comment]
Hi!
Is it the beta version (new interface) or the older version? Could you
please send a screenshot?

In any case, I think you should reinstall the app.
Thanks

**Comment by ThomasRitter75** [comment]
Installed via Play Store

Screenshot you asked for:
![screenshot_20180807-152028](https://user-images.githubusercontent.com/16209768/43778315-a4ca16fa-9a55-11e8-82e3-f7ef007156b3.png)

I reinstalled the app as you said and it works again. Thanks! If you want this issue closed, is your decision.
