### ISSUE TITLE
Add an option to add the app to Doze whitelist

### ISSUE THREAD

**Issue by yuriykulikov** [yuriykulikov/AlarmClock#306]
https://developer.android.com/reference/android/provider/Settings.html#ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS

**Comment by revuwa** [comment]
I really don't think you need it. I just wanted to link a (working example) from another project, for showcase reasons or something:
https://github.com/fennifith/Alarmio/blob/master/app/src/main/java/me/jfenn/alarmio/data/preference/BatteryOptimizationPreferenceData.kt

**Comment by yuriykulikov** [comment]
@revuwa it is not clear if this is required. I am still gathering info.

**Comment by yuriykulikov** [comment]
Not required. Closed.
