### ISSUE TITLE
[Discussion] - How can I step by step learn and understand the code base ?

### ISSUE THREAD

**Issue by trungnguyen22** [yuriykulikov/AlarmClock#312]
I already have some experiences with Android Development, but still find it is so difficult to understand the code base, maybe it is so advance to me. What I want to know is:

- Can you give a real quick explanation on how things go in README ? So learners can have some clues.
- Which architecture is used in the project ? - so that I can research about it
- What are perquisite knowledge we have to learn first to understand the code ?

**Comment by yuriykulikov** [comment]
Hi,
I can probably improve the documentation, but first in the end of August.

In the meantime a good starting point would be Application class. There you
will see a Store which is the backbone of the UI and AlarmManager which
holds AlarmCores. I will try to add some information before I go on
vacation.

**Comment by yuriykulikov** [comment]
@trungnguyen22 are you still interested?

**Comment by yuriykulikov** [comment]
I guess not.

**Comment by aggarwalpulkit596** [comment]
@yuriykulikov Could you help me out and tell me how this thing works even if the app is in a killed state and that too for Chinese ORM's i have tried multiple things in my career so far but nothing works like this? We could make this a library whose sole purpose would be to set tasks like work manager.

**Comment by yuriykulikov** [comment]
Hello,
the app sets alarms using AlarmManager. That is all, no other measures are
necessary.
