### ISSUE TITLE
Label presentation

### ISSUE THREAD

**Issue by n49o7** [yuriykulikov/AlarmClock#313]
In all of the three layout styles, the label of each alarm seems out of place.

- Compact : the label is pushed towards the bottom and clipped.
- Bold : the label is pushed at the very top left of the item, instead of somewhere near the time.

**Comment by yuriykulikov** [comment]
Clicking behavior has been changed. I don't have any idea about improvements though.

**Comment by n49o7** [comment]
![Screenshot_Simple_Alarm_Clock_20190909-180102](https://user-images.githubusercontent.com/879059/64546983-fb056500-d32b-11e9-8daa-f380bf4025a1.png)
![Screenshot_Simple_Alarm_Clock_20190909-180050](https://user-images.githubusercontent.com/879059/64546985-fb056500-d32b-11e9-9136-3f4c45f0b209.png)

Screenshots to illustrate. Is is specific to my device ?

**Comment by yuriykulikov** [comment]
Hello,
This is limited to a small set of devices and I cannot understand why. It
seems that font scaling does not work properly.

**Comment by n49o7** [comment]
This seems to be fixed now.
