### ISSUE TITLE
Inconsistent tapping targets

### ISSUE THREAD

**Issue by n49o7** [yuriykulikov/AlarmClock#314]
All three layout styles make it difficult to know where to tap.

- Classic : Accidentally tapping the label will open the details.
- Compact and Bold : the three dots and the toggle are too close to each other.

**Comment by yuriykulikov** [comment]
I have changed it in 3.05.05 Please check if it ok.5

**Comment by n49o7** [comment]
We should probably include #313 in this discussion.

I don't know if this is specific to my phone, but I have this :

![alarm_current](https://user-images.githubusercontent.com/879059/62835329-77d2ef80-bc57-11e9-8e85-6d26506db348.jpg)

From what I understand, it is caused by the fact the the details now unfold from underneath an entry, instead of going to another screen. However, a little tidying up can go a long way. I have summarized my suggestions below :

![alarm_proposed](https://user-images.githubusercontent.com/879059/62835331-799cb300-bc57-11e9-9277-9d21e4ed093e.jpg)

I hope it's concise enough.

**Comment by yuriykulikov** [comment]
Classic is already like this in version 3.05.05. I think I like your suggestion for compact, but I am not sure about bold. I will look into it in 2 weeks after my vacation.

**Comment by yuriykulikov** [comment]
Classic and compact are also more like what you are describing in 3.05.05.

**Comment by n49o7** [comment]
Ah ok, I rely on Store updates, as I'm not setup to compile.

**Comment by yuriykulikov** [comment]
It is rolling out presently.

**Comment by n49o7** [comment]
I currently have 3.05.06 and can confirm that this is solved.
