### ISSUE TITLE
Question: How does this app work when the task is removed?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [yuriykulikov/AlarmClock#320]
All alarm manager samples I've found fails to have the alarm being triggered in case the app's task is removed from the recent tasks.
 
I might be wrong about this, but I think that somehow this repository succeeds and it still lets the alarm be triggered after I remove it from the recent tasks:

How come?
What does it have that the others don't?

I tried for example to call this code directly:

```kt
            val alarmManager = activity!!.getSystemService(Context.ALARM_SERVICE) as AlarmManager
            val setter = AlarmSetter.AlarmSetterImpl(logger, alarmManager, activity)
            val calendar = Calendar.getInstance()
            calendar.add(Calendar.SECOND, 10)
            setter.setUpRTCAlarm(1, "asd", calendar)
```

And it works (I made AlarmsReceiver to print to the logs, and saw it reached it), but when I remove the app from the recent tasks, it doesn't.
This means that something on the way helps it keep the alarm even when the app is removed from the recent tasks.

I even tried to update the targetSdk to 29, and other than needing to add the `<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />` into the manifest, it worked fine.

Can you please answer on this?
I've tried to investigate this issue for a long time (asked [here](https://stackoverflow.com/q/60079472/878126)).

**Comment by yuriykulikov** [comment]
Hey,
I have answered on Stackoverflow. Basically look into AlarmSetter and copy
everything from there.
Let me know if you it did not work out.

**Comment by yuriykulikov** [comment]
Ah now I see you have tried calling my code and it didn't work. Please
check that you have all permissions that I have and that you are sending
the intent to a broadcast receiver.

**Comment by AndroidDeveloperLB** [comment]
Hello and thank you for trying to help.
Sadly what you wrote doesn't work for me, even if I copy the permissions and grant them (using "-g" as parameter). I don't think it even needs any of those permissions.

Anyway, attached here a sample project (repository [here](https://github.com/AndroidDeveloperLB/AlarmClockSample))  and a video to show the issue.
Please have a look and let me know what you see here that's wrong.
[2020-03-01_23-11-48.zip](https://github.com/yuriykulikov/AlarmClock/files/4272443/2020-03-01_23-11-48.zip)

[AlarmClockSample.zip](https://github.com/yuriykulikov/AlarmClock/files/4272442/AlarmClockSample.zip)

When I added logs into your repository's receiver, it worked fine even if I remove the app from the recent tasks.
When I try to remove the sample app I've made from the recent tasks, it completely removes all alarms that were set.

**Comment by yuriykulikov** [comment]
I have checked out the application.
My steps were:
1. Launch the app
2. Observe no alarm icon near the clock
3. Click "schedule"
4. Observe alarm icon appeared near the clock
5. Close the app and remove from recents
6. Observe alarm icon is still near the clock

The issue is not reproducible on Moto Z2 Play.

Can you confirm that the same sequence works differently on your device? Can you confirm that SimpleAlarmClock keeps scheduled alarms in this scenario?

**Comment by AndroidDeveloperLB** [comment]
I don't have this device.
I have emulators and Pixel 4.
Watch the video. It shows the behavior.
The icon appears, and when you remove the app from the recent tasks, it gets removed. It doesn't stay.

**Comment by Cheticamp** [comment]
FWIW I tried to replicate this using the supplied app with the 10s delay and the Google Pixel 2 emulator running API 29. The only difference that I see is that I had to back off to Gradle 3.6.1 since I am running Android Studio 3.6.1. Following the same sequence of events (set alarm, check it, wait for alarm, set another alarm, check it, swipe from recents before alarm) and it works. I can post a video if anyone cares to see it.

I don't know what is going on with these alarms, but I have struggled with this same issue in the past and would welcome a solution or, at least, an explanation.

**Comment by AndroidDeveloperLB** [comment]
How come it works for you?
I tried again, with v3.5.3 and v3.6.1 of gradle and it still doesn't work.

Here, attached again.
Please show a video. Maybe you don't do as what I did.
[2020-03-02_19-07-58.zip](https://github.com/yuriykulikov/AlarmClock/files/4276767/2020-03-02_19-07-58.zip)

[AlarmClockSample.zip](https://github.com/yuriykulikov/AlarmClock/files/4276766/AlarmClockSample.zip)

BTW, I wanted to ask: is it ok to use null for "pendingShowList" in this line:

```kt
manager.setAlarmClock(AlarmManager.AlarmClockInfo(timeToTrigger, pendingShowList), pendingAlarm)
```
The alarm we plan to use doesn't need to be opened. It's doing some very short work after some given duration.

**Comment by Cheticamp** [comment]
Here is a screen recording (webm file inside the zip) showing the actions I took and what happened. As I mentioned, I made no changes to your app other than the change to Gradle 3.6.1. 

[Pixel_2_API29_recording.zip](https://github.com/yuriykulikov/AlarmClock/files/4277026/Pixel_2_API29_recording.zip)

**Comment by AndroidDeveloperLB** [comment]
But that's impossible.
I tested multiple times...

Could it be that it occurs only when connected to PC ? Please try to connect device to the PC while looking at the logs (it prints to both logs and toasts).

Can you please also try on emulator?

**Comment by Cheticamp** [comment]
That was an emulator. The logs show that everything worked during the emulation. I just tried it on a Samsung S7 (Android 8.0.0) and it worked connected to the PC and when not connected, I used your app [here](https://github.com/yuriykulikov/AlarmClock/files/4276766/AlarmClockSample.zip). There is nothing else that is special with my setup.

I don't have a clue what is going on. Maybe you could supply your APK file? I could try to load it directly to see if that works.

**Comment by AndroidDeveloperLB** [comment]
Hmmm... I think it occurs on multiple cases:

1. Run directly from the IDE.
2. Have null or pendingAlarm instead of pendingShowList in this code:

```kt
            val pendingShowList = PendingIntent.getActivity(this, 100500, Intent(this, AlarmsListActivity::class.java), PendingIntent.FLAG_UPDATE_CURRENT)
            manager.setAlarmClock(AlarmManager.AlarmClockInfo(timeToTrigger, pendingShowList), pendingAlarm)
```

I think it doesn't occur if I run the app via the launcher, AND have pendingShowList as the one to be used.
I think that even number 2 might not be needed.

Can you please try via the IDE ? Don't launch via launcher. Only via IDE.

**Comment by yuriykulikov** [comment]
pendingShowList might be relevant. Perhaps Android checks if your AlarmClockInfo has a valid pending intent. I remember something related to it... It was so much digging to make it work reliably on Android 8 so I don't even remember anymore what was necessary.

**Comment by Cheticamp** [comment]
Run from Android Studio and via launcher for S7 and emulator. All ways worked for me.  I didn't change the code.

**Comment by AndroidDeveloperLB** [comment]
This is odd. Maybe the reason that some other alarm clock apps have this issue is that they didn't provide a good PendingIntent for AlarmClockInfo (or null) , then ? 

See this alternative app for example:
https://play.google.com/store/apps/details?id=com.simplemobiletools.clock
It has this issue too (and is open sourced).

Searching for "AlarmClockInfo" , I don't even get a result.

I think I've finally found the cause to this issue though:
I use Canary version of Android Studio, and somehow it causes it.
See the videos I've made here comparing between canary and stable :
https://issuetracker.google.com/issues/150080941#comment5

I think "null" can be used for the PendingIntent of AlarmClockInfo. Doesn't seem to cause issues after all.

I don't know what to do about the bounty now. Was sure I'm just not implementing it well...

What do you think?
Can you please check on Canary too?

**Comment by Cheticamp** [comment]
Android Studio 4.1 Canary 1 with clean install of app. Pixel 2 emulator API 29. App fails when starting from IDE but succeeds when starting from launcher.

**Comment by AndroidDeveloperLB** [comment]
So you confirm that what I said seems correct?

**Comment by AndroidDeveloperLB** [comment]
BTW, if I run the app from the project (of the current repository), via the IDE, I actually can reproduce the issue.
