### ISSUE TITLE
Make on/off status in the AlarmList more visible

### ISSUE THREAD

**Issue by bernasconi** [yuriykulikov/AlarmClock#324]
It would be clearer if the text for alarms that were switched off was in a much darker grey on the list-of-alarms page, so the switched-on alarms stand out. The on-off slider is not very obvious, particularly if your colour sight isn't great.

Switched off alarms should arguably go at the bottom of the list, because they will be the last ones to go off (i.e. never).

**Comment by yuriykulikov** [comment]
# Make on/off status in the AlarmList more visible
Use background color and/or text color color to change how the alarm row looks when on and off

## Motivation
Slider which changes color from grey to primary is small and is easy to miss

## Description
Some changes of color, for example text color can be used to increase the visibility of switched on alarms.

- [ ]  Check other apps and see how they are doing it

## Risks and Assumptions
Users can become annoyed by yet another design change.

**Comment by yuriykulikov** [comment]
Done in redesign branch.
