### ISSUE TITLE
Question: How does the app get "Show on lock screen" and "Display pop-up windows while running in the background" permissions?

### ISSUE THREAD

**Issue by DeNatur** [yuriykulikov/AlarmClock#328]
Hi,

Could you tell me how did you manage to get Xiaomi permissions "Show on lock screen" and "Display pop-up windows while running in the background"?
![permissions2](https://user-images.githubusercontent.com/28963517/91851542-a7d4a280-ec5f-11ea-938f-155a4d3d64cc.jpg)
I could not find any source of those permissions and saw that this app automatically grants them.
I looked through the source code I did not see how to do this.

Thanks!

**Comment by yuriykulikov** [comment]
Hi,
I don't use these permissions.
Take a look at
https://github.com/yuriykulikov/AlarmClock/blob/develop/app/src/main/java/com/better/alarm/background/NotificationsPlugin.kt

It is a high-prio notification with an activity attached to it.

I hope this helps.

Best wishes,
Yuriy

**Comment by yuriykulikov** [comment]
@DeNatur Since Android 10 a new Permission is required. Check this out: https://developer.android.com/reference/android/app/Notification.Builder#setFullScreenIntent(android.app.PendingIntent,%20boolean)
