### ISSUE TITLE
Customizable pre-alarm

### ISSUE THREAD

**Issue by ethaden** [yuriykulikov/AlarmClock#334]
It would be cool if the pre-alarm would be configurable individually for each configured alarm, with (at least) the following options:
- individual configuration of the pre-alarm duration
- optionally custom pre-alarm sound (independent from the main alarm sound)
- optionally the gradually increase of volume during the pre-alarm

**Comment by AhmadullahSaikat** [comment]
Agree with you.

**Comment by yuriykulikov** [comment]
Will be tracked as #32
