### ISSUE TITLE
Make it a library.

### ISSUE THREAD

**Issue by AhmadullahSaikat** [yuriykulikov/AlarmClock#335]
Please make the project as a library.
So that, we can pass alarm key, alarm name, alarm time, repeated days, ringtones etc.
And delete alarm by using alarm key.

**Comment by yuriykulikov** [comment]
Hello @AhmadullahSaikat, unfortunately I do not have time and resources for such undertaking. I barely manage to support this project. You are free to fork the project and derive a library out of it.
