### ISSUE TITLE
How to set custom alarm tone from asset?

### ISSUE THREAD

**Issue by AhmadullahSaikat** [yuriykulikov/AlarmClock#339]
`alarmtone = Alarmtone.Sound("file:///android_asset/alarm.mp3"),`

this code not working for me,

**Comment by yuriykulikov** [comment]
Hello,
do you mean assets built into the app or playing files from the SD Card?
Asset is a file which is built into the application (hardcoded).
Playing MP3 files is different.
Cheers

**Comment by AhmadullahSaikat** [comment]
I want to play alarm from asset or raw folder.
My Code is here: 
```
alarmtone = Alarmtone.Sound("file:///android_asset/custom_alarm.mp3") // from asset
alarmtone = Alarmtone.Sound("android.resource://" + requireContext().getPackageName() + "/raw/custom_alarm.mp3") // from raw folder


```

But for asset folder, alarm tone plays default sound & for raw folder alarm tones are silent.

How to solve this issue. No documentation available for this.

**Comment by AhmadullahSaikat** [comment]
How to set alarm tone from asset folder?

**Comment by yuriykulikov** [comment]
To play the tone from an Asset use:
```
        resources.openRawResourceFd(res)?.run {
            player?.setDataSource(fileDescriptor, startOffset, length)
            close()
        }
```

As seen here: com.better.alarm.background.PlayerWrapper#setDataSourceFromResource

Example use:
```player.setDataSourceFromResource(R.raw.fallbackring)```
