### ISSUE TITLE
Set alarm for a specific date 

### ISSUE THREAD

**Issue by ghost** [yuriykulikov/AlarmClock#341]
some reasoning copied from here:

https://github.com/SimpleMobileTools/Simple-Clock/issues/127

>It's a common use case (for me at least) to create a one-time alarm that goes off on a specific date and time. For example if I have to get up early for a flight, job interview, etc (basically any non repeating event). Sometimes the event is more than a week ahead and would love to be able to create these kinds of alarms like I can with the stock alarm app.

>(Calendar) notifications don't loop based on my experience and I prefer setting the notification volume at 0% to avoid distractions. Last I tried the longer audio track I had set as the notification sound was also cut off very quickly (15 seconds or less).
>
>In my opinion notifications aren't a replacement for alarms and apparently are almost as easy to miss as a typical SMS sound or similar. Would you rely on a single 0,5 second \*ping* sound effect for your alarm?

**Comment by yuriykulikov** [comment]
# 🚀  Alarms for a specific dates

Allow to create a one-time alarm that goes off on a specific date and time
## Motivation

> Sometimes the event is more than a week ahead and would love to be able to create these kinds of alarms like I can with the stock alarm app.

This seems to be useful for one-off events like getting up to see a doctor, get on a plane, etc.

## Description
Add a new type of repeating, which is set to a particular date. The UI can be implemented by adding swipe with tabs to the repeat popup. Alarm will be disabled or deleted after it has fired.

**Comment by yuriykulikov** [comment]
I think we can implement this without changing the database layout. But I am struggling with the design for the feature. How should it look like?

**Comment by jp9856** [comment]
I can begin work on this. I'm thinking about a row in the AlarmDetailsFragment that, when clicked, opens up a DatePickerDialog and allows the user to pick the date. This would delete the "Repeat" row because having both doesn't really make sense. Then, just fiddling around with the code to enter the alarmtime in the database as the date chosen. Let me know if you'd prefer the default date picker dialog or a custom one like the TimePickerDialog you have set up.

**Comment by yuriykulikov** [comment]
I would argue that you probably shouldn't change the database layout for this. Consider reusing the repeat field. Otherwise the database upgrade has to be implemented which is not an easy task.

**Comment by yuriykulikov** [comment]
Regarding the UI: perhaps it can be implemented with a single row in the details fragment, which is named "Repeat or date". When clicked, a dialog will be popped, which has tabs "repeat" and "date" at the top. What do you think about that?

**Comment by jp9856** [comment]
I like the idea for the UI! And what you're saying about the database makes a lot of sense, I think there's definitely a way to use the repeat column to implement this. I'll get started on that and keep you posted if I run into anything
