### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [yuriykulikov/AlarmClock#342]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by Korb** [comment]
Screenshots are still not showing up on [the app page in F-Droid](https://f-droid.org/packages/com.better.alarm/).

![Screenshot_2023_0401_124300](https://user-images.githubusercontent.com/3509797/229278642-fd88eab2-55b2-4c93-a559-0085a66fc34b.jpg)
