### ISSUE TITLE
F-Droid last version is still 3.05.05 from 12th March 2020

### ISSUE THREAD

**Issue by falzonv** [yuriykulikov/AlarmClock#350]
Hello,

First of all, thank you very much for providing this application. I really like it, especially the fact that a basic click is enough to stop the alarm (was much more tedious with the default alarm app on my phone).
Very good work!

## Describe the bug

I was about to create a feature request asking for a notification to skip the next occurrence of a recurring alarm, but when looking at tickets #14 and #141 which are closed, this feature seems already implemented.

However, I am using the last version available on F-Droid (3.05.05 from 12th March 2020) and this feature is not part of it.
When looking at the GitHub tags, I see the most recent version is 3.07.00 from 29th September 2020 but this is has not been integrated in F-Droid repository apparently.

## To Reproduce

Open the F-Droid website on https://f-droid.org/en/packages/com.better.alarm/ and check the last version available (the same information is displayed on the Android client).

## Expected and observed behavior

**Expected:** the last version should be 3.07.00 from 29th September 2020 (most recent tag in GitHub currently).
**Observed:** it is version 3.05.05 from 12th March 2020.

## Screenshots
Not applicable.

## Logs
Not applicable.

---

Could you please check what is wrong with the F-Droid update?

Thank you again for the app and have a nice day.

Best regards.

**Comment by yuriykulikov** [comment]
Hello,
I have created a merge request here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8638

Let's see how that goes :)

**Comment by falzonv** [comment]
Great, thank you!

**Comment by yuriykulikov** [comment]
@falzonv it seems that all what was required is to set the version directly. See discussion on F-Droid: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8638

**Comment by falzonv** [comment]
Hello,

Perfect, thank you very much for the correction!

Best regards.

**Comment by yuriykulikov** [comment]
Ok, it was done today: https://gitlab.com/fdroid/fdroiddata/-/commit/81d6b77625bf401c0180b3831c3562e366710e54

@falzonv thank you for reporting this.

**Comment by falzonv** [comment]
Hello,

Just to confirm that I was able to install version 3.07.01 from F-Droid few minutes ago and the "Skip alarm notification" feature is exactly what I needed and was missing from the previous version :-)

Thank you again!

Best regards.
