### ISSUE TITLE
Allow dictionary & start label with upper case

### ISSUE THREAD

**Issue by ltguillaume** [yuriykulikov/AlarmClock#358]
# Allow dictionary & start label with upper case

## Summary

1. It would be nicer to have the keyboard's dictionary (suggestions) working for the Label field.
2. Currently, when entering a label, the first letter will be lower case. Esthetically it would be more pleasing to start with an upper case, because the repeat info also starts with an upper case.

## Motivation

Usability, esthetics and consistency 😛

## Description

1. Add an alarm
2. Tap "Label"
3. Start typing (keyboard will not show suggestions and it will start with a lower case character by default).

_Using v3.07.01 F-Droid_

**Comment by ltguillaume** [comment]
Added request for allowing keyboard dictionary (suggestions).

**Comment by yuriykulikov** [comment]
Hm, it works as you suggest on my phone. Any idea what might be different on yours and how can this be implemented?

**Comment by ltguillaume** [comment]
Some keyboard apps can force suggestions, perhaps yours does.

Should be fixed by changing
https://github.com/yuriykulikov/AlarmClock/blob/add5ae8512f57088dffdd04bfc9fcb8f1622f393/app/src/main/res/layout/details_fragment_lower.xml#L125
to
```
android:inputType="textCapSentences"
```

**Comment by yuriykulikov** [comment]
Fixed, thank you @ltGuillaume !
