### ISSUE TITLE
Delete alarm when going off

### ISSUE THREAD

**Issue by IceflowRE** [yuriykulikov/AlarmClock#361]
# Delete alarm when going off

## Summary
Add an toggle to delete an alarm when it goes off.

## Motivation
Never again a full list of old unused alarms. No need to clean the list up anymore.

## Description
Just a toggle at the creation screen,.

**Comment by yuriykulikov** [comment]
Should this be hidden when repeat is set?

Should this have an impact on the alarm pop-up (for example rename "dismiss" into "delete")?

Should such alarms be marked in the list somehow?

Also, could you please provide translations for English, German, Italian, Spanish and any other languages you would like 😉

**Comment by IceflowRE** [comment]
> Should this be hidden when repeat is set?

Yes. As it makes no sense in that case.

> Should this have an impact on the alarm pop-up (for example rename "dismiss" into "delete")?

No, the decision was made beforehand. No need to rephrase it. And to bother the user.

> Should such alarms be marked in the list somehow?

I think it is totally fine to not explicitly mark them and just show it inside the editing screen.

> Also, could you please provide translations for English, German, Italian, Spanish and any other languages you would like 😉

English: `Delete after goes off`
German: `Nach Ausführung löschen`
Italian: `Elimina la sveglia una volta suonata`
Spanish: `Eliminar cuando suene la alarma`

**Comment by AeliusSaionji** [comment]
looking forward to this!

I use simple alarm clock with this app, I end up with a huge laundry list of alarms to delete.  
https://gitlab.com/antonok/warpclock

**Comment by yuriykulikov** [comment]
Done
