### ISSUE TITLE
Message "Alarm set ... from now" gone

### ISSUE THREAD

**Issue by ltguillaume** [yuriykulikov/AlarmClock#362]
## Describe the bug
The new v3.08.08 does not have show a toast anymore that shows when the alarm you just set is about to go off.
This may have to do with #352, but currently it's just removed altogether.

## To Reproduce
Create an alarm or change the time of an existing one. No "Alarm set ... from now" toast will show up.

## Expected and observed behavior
A toast that show the  "Alarm set ... from now" countdown in order double-check that you've set the alarm right.

**Comment by kolanse** [comment]
That is what i am currently working on. please see the comments on issue #352  for feedback. Thank you

**Comment by ltguillaume** [comment]
Aaah great, thx, hopefully this will be integrated soon.
