### ISSUE TITLE
Logs: Add a file ring buffer writer and cleanup the logs

### ISSUE THREAD

**Issue by yuriykulikov** [yuriykulikov/AlarmClock#365]
#  Logs: Add a file ring buffer writer and cleanup the logs

## Summary
Logs: Add a file ring buffer writer and cleanup the logs

## Motivation
There will be less irrelevant logs to read through, but we will  have information from previous runs.

## Description
Carefully examine a log and see what is redundant and can be removed or joined.
Add an slf4j logger, add a logback logger which logs to a file and to the logcat

## Drawbacks, risks and assumptions
We can hide crucial information.
Files can be become too big or leak

## Rationale and alternatives
Just clean up the logs would also be possible.

**Comment by kolanse** [comment]
okay @yuriykulikov  can i work on this?

**Comment by yuriykulikov** [comment]
Sure. Take a look at logback I guess.

**Comment by kolanse** [comment]
yeah i will . thank you

**Comment by yuriykulikov** [comment]
Let me know if you have trouble with the logger we have in the app. To make sure that we are on the same page: the logger itself should not be changed, nor any other classes in the app. But the implementation of the logger can be replaced with something which delegates to an slf4j logger with a logback behind it. Then logback should log into the logcat and into a ring buffered file. This file should then be added to acra report.

**Comment by kolanse** [comment]
Alright . Sorry i have been busy for the past few days with interviews and work .. will take a look tomorrow and give you feedback if i encounter anything i need clarity on.

**Comment by yuriykulikov** [comment]
Sure, take your time. Any contribution is welcome and there is no pressure
at all. I don't know what your experience is, I gladly support students and
developers who start their careers, so don't hesitate to ask if you have
any questions. Cheers

**Comment by kolanse** [comment]
Thank you very much. I appreciate it

**Comment by kolanse** [comment]
@yuriykulikov  did a little bit of research on the comment where you talked about adding  slf4j logger to the application. i discovered this library that makes it possible to add it to an android project. this is the[ android library](https://github.com/tony19/logback-android) . so i was wondering is it okay to add it

**Comment by yuriykulikov** [comment]
Looks promising! Good find😉

I guess we are looking at the Rolling FileAppender? https://github.com/tony19/logback-android/wiki/Appender-Notes#configuration-in-code

Also, I very much prefer confutation in Code over XML😃

And we should keep the Logger interface which is already there.

**Comment by kolanse** [comment]
alright nice . i will try it out

**Comment by yuriykulikov** [comment]
I will takeover, because I need this for the next release. I will use logback-android found by @kolanse . Cheers

**Comment by kolanse** [comment]
Thank you @yuriykulikov  . I will be very much interested in knowing how it works

**Comment by yuriykulikov** [comment]
@kolanse check this out: https://github.com/yuriykulikov/AlarmClock/pull/384
