### ISSUE TITLE
Labels and Repeat not fully visible

### ISSUE THREAD

**Issue by ltguillaume** [yuriykulikov/AlarmClock#366]
1. When scrolling all the way to the bottom, the Repeat options are partly invisible (Compact, Bold and Classic style):
![image](https://user-images.githubusercontent.com/4777345/126897117-b5a6ee52-de77-4efc-97df-f738b2ea1e96.png)
2. When selecting many repeat days, the label becomes partly invisible (Compact and Classic style):
![image](https://user-images.githubusercontent.com/4777345/126897154-e5868d0c-0ab6-423d-abf3-c9a945bee6cf.png)

**Comment by kolanse** [comment]
yeah this can be probably fixed by proper padding

**Comment by yuriykulikov** [comment]
Thanks for pointing this out. Fixed.
