### ISSUE TITLE
A layout adaptation problem

### ISSUE THREAD

**Issue by EasyVector** [yuriykulikov/AlarmClock#369]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure below, on the layout style and theme panel, **texts of the last choice could not be seen fully for both layout style and theme**. This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**.
Because of some problems with my eyesight, I often use the largest font and display.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

App version is 3.09.01, my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. Thank you so much!!

**Expected behavior**

I hope that I can see all of the texts on the layout style and theme panel, and in this circumstance, some of them be seen fully.

**Steps to reproduce the behavior:**

1.use the largest font and display in the display setting
2.click the layout style and theme panel on the main page
3.this error could be seen

**Screenshot**

<img src="https://user-images.githubusercontent.com/25502419/128964932-a5e7d06b-7cbd-43ae-a1de-9fbc2d20a585.png" alt="Screenshot_1628651704 copy" width="250"/>

**Environment**

1. Version of Simple Alarm Clock: 3.09.01
2. Device : Google Pixel 2,
3. OS version : Android 10.0

**Comment by yuriykulikov** [comment]
Merged the PR, closing the issue. Thank you!
