### ISSUE TITLE
Snackbar is displayed under navigation bar

### ISSUE THREAD

**Issue by falzonv** [yuriykulikov/AlarmClock#372]
Hello,

## Describe the bug

On my phone (Android 8.1, Motorola G5 Plus), the snackbar from #352 is displayed *under* the transparent navigation bar which makes it quite difficult to read as the text becomes mixed with navigation buttons (see screenshots).

## To Reproduce

- Create a new alarm
- Validate the time and the settings to display the snackbar
- The snackbar appears under the navigation bar (see screenshots)

## Expected and observed behavior

Expected: the snackbar should be displayed above the navigation bar to be easily readable
Observed: it appears under the navigation bar (see screenshots)

Although it might be version-specific, this is probably not related to my phone because I see another app (Nextcloud Notes) displaying snackbars above the navigation bar as expected.

## Screenshots

<img src="https://user-images.githubusercontent.com/4698531/129459348-2187574b-7798-4d06-8881-dbdbd75f1c01.png" width="50%"/>

When using a blue light filter (Red Moon in this case), the text is even more difficult to read
<img src="https://user-images.githubusercontent.com/4698531/129459201-6e41eb56-c877-47a6-9db8-18e8f26ebf00.png" width="50%"/>

## Logs
Not applicable.

## Other remarks

Thank you again for making this app!

Best regards.

**Comment by yuriykulikov** [comment]
Thank you! I can reproduce this on Pixel as well when switching to "'3 button" navigation bar.

**Comment by yuriykulikov** [comment]
@kolanse would you like to take a look or should I take over? Cheers

**Comment by kolanse** [comment]
@yuriykulikov  i would take a look . Thank you

**Comment by falzonv** [comment]
Great, thank you for the quick replies!

*For information, I will be away from Internet and GitHub for a couple of weeks so don't be surprised if I do not reply soon once the problem is solved (I will discover it only when returning).*

**Comment by yuriykulikov** [comment]
@kolanse I was working on something else and found a fix for this issue. I will open PR for you to take a look at. BR.

**Comment by falzonv** [comment]
Hello @yuriykulikov,

Just installed version 3.09.08 and the fix works perfectly, thank you very much!

Best regards.
