### ISSUE TITLE
Default Alarm ringtone takes you to phone ringtone on Samsung phones

### ISSUE THREAD

**Issue by timonoj** [yuriykulikov/AlarmClock#386]
Default Alarm ringtone setting takes you to the phone's ringtones section, which has multiple ringtones available for each sound mode (loud, silent, vibration only etc)...but none seem to affect the alarm's default ringtone. It's actually not clear what to choose from there. 

The default alarm seems to be 'homecoming', but nowhere else in the phone settings is this ringtone chosen. And there doesn't seem to be a way to change this default in the alarm settings. At least on Samsung phones. Tested in a s10e running Android 11. But also in an s8+.

**Comment by kyoforkshomebrews** [comment]
Having the same problem on a Huawei P Smart 2019.

**Comment by Gatienzo** [comment]
Same problem in Android 13 Samsung phone. 
Great app BTW. Thanks
