### ISSUE TITLE
How do I set a custom alarm clock ringtone?

### ISSUE THREAD

**Issue by SerhiiVynohradov** [yuriykulikov/AlarmClock#393]
I know it's not a bug, but before I spend 3 hours trying to figure out how everything works, can anyone just give me a hint?

How do I set custom alarm clock sounds?

I don't want the default sounds, don't want system sounds.

I want to basically just record .ogg files on my computer, put them inside this program (res/raw folder or whatever), and tell the program to only show my recorded sounds as the only selection options, and I do not want it to show anything else (any system sounds, etc).

I would be very grateful.

**Comment by yuriykulikov** [comment]
Hello,
You need a app for that (if not on a pixel device). Try looking for a
Ringtone Manager in the app store.
Cheers
