### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by MartinX3** [yuriykulikov/AlarmClock#410]
# Awesome backuuuuuuuup :)

## Summary
Please add a backup option

## Motivation
I use a custom rom without google with microG.
It would be nice to backup my timers in the cloud or in a json file or something else.

## Description
I want automatic backups on every alarm edit, add, delete.
As export to a folder path or in my google cloud space.

## Drawbacks, risks and assumptions
Privacy.
Maybe the backups should get encrypted by OpenKeyChain on the phone.
https://www.openkeychain.org/

## Rationale and alternatives
Backups by https://github.com/machiav3lli/oandbackupx

**Comment by yuriykulikov** [comment]
It seems that given current trends we won't have to implement this. Anyway, without an internet permission it is not viable and we will not introduce a permission just for this feature.
