### ISSUE TITLE
update to target SDK 31 will cause android.app.ForegroundServiceStartNotAllowedException

### ISSUE THREAD

**Issue by GordonWu** [yuriykulikov/AlarmClock#413]
Just update Gradle targetSDKVersion and compileSDKVersion both 31
setup alarm and lock screen wait to alarm alert, when alarm alert at time it will get crash 

android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false 

and i investigation find it start from AlertServicePusher.kt line 37
in Pixel 5a 5G (android 12) but Pixel 3XL (android 12) is fine

**Comment by yuriykulikov** [comment]
We have target sdk 31 and 33 and it works.
