### ISSUE TITLE
Please increase font size for "am"/"pm" text for alarm times

### ISSUE THREAD

**Issue by ardugitter** [yuriykulikov/AlarmClock#414]
Please could you increase the font size for "am"/"pm" text for alarm times? Or at least make it customisable?

I keep misreading the tiny am/pm text and the next day find my alarm has not gone off because it was set to 7pm, not 7am! (Obviously I am referring to the case where I enable an existing alarm. If I just created the alarm I know what time I set of course.)

This will allow me to wake up on time more often. :-)

Thank you for your simple and excellent app.

**Comment by yuriykulikov** [comment]
Hello @ardugitter,
could you please upload a screenshot? The app looks slightly different on different devices.

**Comment by ardugitter** [comment]
![Simple_Alarm_Clock](https://user-images.githubusercontent.com/73884126/159087260-b66900d8-ec89-4af3-95e5-6f520ab8ead1.png)

Here you go. Thanks.

**Comment by yuriykulikov** [comment]
![image](https://user-images.githubusercontent.com/827794/163671999-adb58e75-b173-4322-8b3c-d163301036d9.png)
@ardugitter how does this look?

**Comment by ardugitter** [comment]
> ![image](https://user-images.githubusercontent.com/827794/163671999-adb58e75-b173-4322-8b3c-d163301036d9.png) @ardugitter how does this look?

That is much better. Thank you. :-D
