### ISSUE TITLE
Do not disturb deactivates vibration

### ISSUE THREAD

**Issue by MartinX3** [yuriykulikov/AlarmClock#416]
## Describe the bug
The phone doesn't vibrate in do not disturb

My old 3rd party alarm app does work in do not disturb mode.

## To Reproduce
Describe the steps to reproduce the behavior:
- Activate do not disturb
- Allow the alarm to workaround it
- Use an alarm

## Expected and observed behavior
- Expected: Vibration and sound
- Observed: Only sound, no vibration

## Screenshots
N/A

## Logs
[application-logs.txt](https://github.com/yuriykulikov/AlarmClock/files/8379936/application-logs.txt)

**Comment by yuriykulikov** [comment]
Hello @MartinX3,
unfortunately for applications targeting newer API levels it is not possible to vibrate in DND (Do not disturb) unless allowed by the user in the phone settings. Older apps can still vibrate because they target older SDK levels.

**Comment by MartinX3** [comment]
Hello @yuriykulikov 
I allowed alarms to turn of DnD.
Is there something else I miss?

**Comment by yuriykulikov** [comment]
Do you have fade in? Try reducing fade in time in settings. On my pixel I have vibration even when DND is activated and alarms are not allowed

**Comment by MartinX3** [comment]
@yuriykulikov I made a mistake. The vibration is not working without do not disturb, too.
That's weird, since every other app is able to vibrate.

**Comment by yuriykulikov** [comment]
Please check if vibration is enabled in the app settings.

**Comment by MartinX3** [comment]
It's enabled.
I also clicked the setting multiple times.
