### ISSUE TITLE
Black screen when the alarm goes off

### ISSUE THREAD

**Issue by PetarBegovic1701** [yuriykulikov/AlarmClock#417]
## Describe the bug
Black screen when the alarm goes off. The UI is not shown, however the long press to dismiss the alarm is working.

## To Reproduce
Set an alarm.
Wait for it to go off.

## Expected and observed behavior
The UI to be visible

## Screenshots
![Screenshot_20220401-111532](https://user-images.githubusercontent.com/25446272/161246595-28d6a044-c809-4888-be82-f1113a42cf8b.png)
![Screenshot_20220401-111546](https://user-images.githubusercontent.com/25446272/161246598-943f51b0-36c5-4efc-b300-2b54209bf3f3.png)

## Logs
Simple Alarm Clock develop 3.10.06 Bug Report of the app with regular updates
[application-logs.txt](https://github.com/yuriykulikov/AlarmClock/files/8396845/application-logs.txt)

Simple Alarm Clock develop 3.10.06 Bug Report of the app with a clean install
[application-logs (1).txt](https://github.com/yuriykulikov/AlarmClock/files/8396851/application-logs.1.txt)

**Comment by nyxkn** [comment]
Can confirm this happens for me as well on one of the two devices I use the app on.

This also happens in another android app I maintain and I think it might have to do with the fullscreen intent notification. If it is triggered when the phone is locked, this seems to happen. Not sure what can be done.

**Comment by yuriykulikov** [comment]
Hello,
is do not disturb mode on?

**Comment by yuriykulikov** [comment]
https://stackoverflow.com/questions/60535947/android-full-screen-notification-wont-show-over-the-lock-screen

**Comment by PetarBegovic1701** [comment]
> Hello, is do not disturb mode on?

As you can see on the screenshots, the disturb mode is not on.
Note that this issue occured with the new version, the older one never had this issue.

**Comment by yuriykulikov** [comment]
It seems that we are doing everything right and the issue does not occur on any devices or emulators I have available. Closing.
