### ISSUE TITLE
How get this permission?

### ISSUE THREAD

**Issue by Viid29** [yuriykulikov/AlarmClock#434]
Hello, such a question "Show on Lock Screen" and "Display pop-up windows while running in the background" is issued in your application when installed from the Play Store.  But when I collect the project from GitHub, they are not issued.  Do I understand correctly that they are issued automatically after moderation of your Google application?

**Comment by yuriykulikov** [comment]
Hello,
my application declares several "normal" permissions and has a few "runtime" permissions. Permissions "Show on Lock Screen" and "Display pop-up windows while running in the background" are covered by this line in the application manifest:
```
    <uses-permission android:name="android.permission.USE_FULL_SCREEN_INTENT" />
``` 

When the user is about to install the application, they are presented with a list of application permissions, which the user has to agree to. Installation is cancelled if the user declines. Therefore, when the application is installed, permissions are granted and cannot be revoked anymore.

You can find some detailed info here: https://guides.codepath.com/android/Understanding-App-Permissions
