### ISSUE TITLE
Make Heads-up notification duration persistent on all devices/OS

### ISSUE THREAD

**Issue by lune856** [yuriykulikov/AlarmClock#439]
# Make Heads-up notification duration persistent on all devices/OS

## Summary
When the alarm goes off, the pop-up window (or heads-up notification) disappears after 5 seconds on some devices/OS. Below are some that I've tested. 

- Galaxy S8 (Android 9) (O) [Persistent- Stays until user hits 'dismiss' button ]
- Android Studio Emulator (Nexus 5x API 31) (O) [Persistent- Stays until user hits 'dismiss' button ]
- Galaxy S20 (Android 12) (X) [Pop-up disappears in 5 seconds then folded into status bar]

Google Clock alarm shows persistent notification while other alarm apps downloaded from PlayStore behaves the same(disappearing in 5 seconds. Eg., Alarm Clock Xtreme by AVG Labs). 

**Suggestions)**
- Any chance we can make the pop-up stay persistent regardless of device/OS version? 
- Maybe show full-screen activity immediately without showing pop-up window?
- **Edits)** _My bad. Just realized that it will show full-screen activity when the screen is locked (or turned off)_

**Comment by yuriykulikov** [comment]
Showing a persistent notification without special permissions ("Draw over other apps") is not possible and it violates Google design rules. Full screen activity is shown if the screen is locked. Therefore closing the issue.
