### ISSUE TITLE
AlarmManager snippet in Java 

### ISSUE THREAD

**Issue by smeet84** [yuriykulikov/AlarmClock#452]
# Integrate ALARM MANAGER code in Java 

I have an issue in an app i am developing for a non profit. I just need the alarm to trigger at a fixed time everyday, however, on ONE PLUS phone Android 10,  it does not trigger.

Code developed here is in Kotlin and uses setRTCAlarm to register for the alarm event, however, i dont see the equivalent in JAVA. 

**Request if someone can guide what can be done, since this app works perfectly fine on ONE PLUS.**

**Comment by yuriykulikov** [comment]
Hello,
you are probably looking for `AlarmManager.setAlarmClock`
