### ISSUE TITLE
Play store release old

### ISSUE THREAD

**Issue by MartinX3** [yuriykulikov/AlarmClock#469]
## Describe the bug
The play store has an old version.
f-droid has the newest git tag version.

## To Reproduce
Compare the f-droid and play store releases.

## Expected and observed behavior
Same version on both stores.

## Screenshots
N/A

## Logs
N/A

**Comment by yuriykulikov** [comment]
Update to play store is rolling out, currently at some 10%

**Comment by yuriykulikov** [comment]
Versions are rolled out.
