### ISSUE TITLE
No alarm at night with battery safe mode and maybe do not disturb?

### ISSUE THREAD

**Issue by MartinX3** [yuriykulikov/AlarmClock#471]
## Describe the bug
I woke up with my old alarm app I want to replace.
The AlarmClock didn't ring.

## To Reproduce
Describe the steps to reproduce the behavior:
- Phone screen off at night with battery safe mode and do not disturb

## Expected and observed behavior
I expected the phone to ring.

But it didn't ring.
I opened the app and the bottom area showing me the next alarm time was empty.
I did need to deactivate and reactivate my alarm to fill this information area with the info about the next alarm time.

## Screenshots
N/A

## Logs
[application-logs.txt](https://github.com/yuriykulikov/AlarmClock/files/8989360/application-logs.txt)

**Comment by yuriykulikov** [comment]
No reproducible.
