### ISSUE TITLE
Alarm not working after reboot on Chinese ROMs

### ISSUE THREAD

**Issue by temanado** [yuriykulikov/AlarmClock#479]
## Describe the bug
Alarm not working after reboot on Chinese ROMs

https://user-images.githubusercontent.com/60067573/189498984-1dc05b59-935e-4594-b499-470384858a87.mp4

Faced a bug.
I turned on the alarm for 22:15, rebooted the phone. In the tray, the alarm clock did not appear. Didn't ring. At 22:15 I opened the application and finished writing a video. At 22:16 the alarm rang)
Video in attachment.

Huawei P smart EMUI 9.1.0 Android 9

**Comment by yuriykulikov** [comment]
Hello,
It appears that you are using another app. Please check the link to Google
play in the readme, you will see that the app looks very different.
