### ISSUE TITLE
Long Press on Snooze does not bring up Time Picker to choose snooze period/time.

### ISSUE THREAD

**Issue by CataCluj** [yuriykulikov/AlarmClock#528]
## Describe the bug
Long Press on Snooze does not bring up Time Picker to choose snooze period/time.

## To Reproduce
Describe the steps to reproduce the behavior:
When any alarm time comes, I get the two buttons to Snooze or Dismiss.
If I understand correctly, a long press on Snooze should allow me to choose when to snooze. Instead I get a window where I can "Turn Off Notiffications"

## Expected and observed behavior
Provide a clear and concise description of what you expected to happen, what has actually happened.

## Logs
Attach the log file which you can create by clicking on the "Bugreport" button in the menu.
![LongPressSnooze](https://user-images.githubusercontent.com/33530615/218562085-52a1baa2-5072-470e-8538-5007f7020ad1.jpg)

**Comment by yuriykulikov** [comment]
Hello,
Long click works only on full screen popup, which is shown when the phone
is locked.
As far as I know, long click in notification cannot be used by the
application.
I hope this helps

**Comment by CataCluj** [comment]
Thank you Yuriy,
In that case, maybe clicking on "Snooze" on the notification should bring up a screen that allows choosing the snooze time.
Optionally, if "Long Press" is required, the Dismiss button should also bring up same new screen where one of the options is "Dismiss" but has to be long-pressed.
Phone is often not locked so the long press functionality is lost both for snooze AND for dismiss which is important because when picking-up the phone one can easily touch the notification and dismiss or snooze by mistake.
AlarmDroid is very similar; it brings up the multiple snooze options (when clickong "Snooze" on the notification) but lacks long snooze availability, that's why I hope yours can be even better.
Even the snooze options should (optionally) require long-press because of same reason when picking up phone, I may snooze instead of dismiss, etc.
I also made a feature request that explains more.
BUT GREAT APP; THANK YOU!
I can try to modify it myself but I'm a bare-metal embedded programmer; mobile is hard for me 🙂

**Comment by CataCluj** [comment]
But you are right that the same notificationcomes up for Alarm Droid at alarm time so maybe that's not a choice that can be made.
However, when clicking on Snooze, instead of doing the default snooze, AlarmDroid takes you to the Snooze-Chooser window.
With some luck and a lot of work (this is hard for me 🙁) I can hopefully do something like that myself if you're not interested, but I hope you are 🙂

________________________________

**Comment by CataCluj** [comment]
If you preffer I can close this as at this point it seems to be more of a feature request than bug even if the snooze-choser is not always gettable.

**Comment by yuriykulikov** [comment]
Closing in favor of #529
