### ISSUE TITLE
calling the dayOfWeek value

### ISSUE THREAD

**Issue by bbbbgggghh** [yuriykulikov/AlarmClock#565]
hello. I have a question for you. I want to sort the alarms by day of the week. To do that, I need to know the dayOfWeek value of each alarm. How do I call this value to AlarmsListActivity?

**Comment by yuriykulikov** [comment]
Hello,
please look for this code in AlarmsListFragment:

```
              val sorted =
                  alarms //
                      .sortedBy { it.minutes }
                      .sortedBy { it.hour }
                      .sortedBy {
                        when (it.daysOfWeek.coded) {
                          0x7F -> 1
                          0x1F -> 2
                          0x60 -> 3
                          else -> 0
                        }
                      }
```

This sorts alarms by day, then by hour and minute

**Comment by yuriykulikov** [comment]
I hope this answers your question. Feel free to reopen is not.
