### ISSUE TITLE
Set clock without UI

### ISSUE THREAD

**Issue by prettygirl20231** [yuriykulikov/AlarmClock#569]
Hello, i want use your clock without open activity.
just like this, i want to set the clock by invoke your method and passing date, hour,minutes directly.
How can i do this?
sorry, i am not native English speaker. I apologize if what I said offended you.

**Comment by yuriykulikov** [comment]
Hello @prettygirl20231,

You can achieve this by sending an Intent https://www.android-doc.com/reference/android/provider/AlarmClock.html#ACTION_SET_ALARM

Something like this:

```
context.startActivity(
        Intent().apply {
          addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
          action = AlarmClock.ACTION_SET_ALARM
          putExtra(AlarmClock.EXTRA_SKIP_UI, true)
          putExtra(AlarmClock.EXTRA_HOUR, 0)
          putExtra(AlarmClock.EXTRA_MINUTES, 0)
          putExtra(AlarmClock.EXTRA_MESSAGE, "From outside")
        })
```

**Comment by yuriykulikov** [comment]
Closing the issue as this is already implemented.
