### ISSUE TITLE
Special permission

### ISSUE THREAD

**Issue by Gravity2106** [yuriykulikov/AlarmClock#583]
## Describe the bug
Provide a clear and concise description of what the bug is.

## To Reproduce
Describe the steps to reproduce the behavior:
Select a new ringtone. Then close and open the app and the popup appears. All permissions have been granted.
Bug report does nothing when I press it

## Expected and observed behavior
The new ringtone should be applied and the Bug report should work

## Screenshots
![cbfdab72-d3be-4d88-881f-7bbdbe8d3a11](https://github.com/yuriykulikov/AlarmClock/assets/45825337/765bdf96-1e3d-4c66-a199-099da12a1184)

## Logs
Attach the log file which you can create by clicking on the "Bugreport" button in the menu.

Thank you

**Comment by secretmango** [comment]
Uhm, I think it would help very much if you could actually fill out the form, try copying the message and translating it to english.

Those texts are placeholders.

I can imagine that a spanish screenshot is not helpful.

**Comment by Gravity2106** [comment]
Thank you for answer. The problem was fixed after update to android 14 (or after on of the last updates of the app, I'm not sure)
