### ISSUE TITLE
App Crashes Immediately After Creating an Alarm

### ISSUE THREAD

**Issue by joseio** [yuriykulikov/AlarmClock#644]
## Describe the bug
Just downloaded and installed the app for the first time today on an up to date Pixel 7. Immediately after creating an alarm, the app crashes. The logs report the following: "... needs to hold android.permission.SCHEDULE_EXACT_ALARM". The only permission the app asks for is Notifications, which I've granted it. Then when I try to open the app, it just hangs at the initial loading screen (the one with just the app logo on it).

## To Reproduce
Describe the steps to reproduce the behavior:
Create an alarm

## Expected and observed behavior
Expect for the alarm to be created successfully and for the app not to crash. 

## Logs
![application-logs.txt](https://github.com/yuriykulikov/AlarmClock/files/13561886/application-logs.txt)

**Comment by yuriykulikov** [comment]
I think this is fixed by 43aff1a52c7c30cc004df0101576da4c486dd03f
