### ISSUE TITLE
Disable the alarm once

### ISSUE THREAD

**Issue by TristisOris** [yuriykulikov/AlarmClock#665]
# Awesome title :)

## Summary
When disable alarm, ask if do it once or permanent.

## Motivation
to disable alarm only for tomorrow.

## Description
same as miui clock.

**Comment by ltguillaume** [comment]
Can't you do that already by long-pressing, then "Skip"?

**Comment by TristisOris** [comment]
probably no.

**Comment by ltguillaume** [comment]
Probably? It's exactly what you want, right? You long-press an active alarm and press "Skip", then the alarm will be disabled for first time it would normally go off, then reinstated. It'll say "(skipping)" in the overview.

**Comment by TristisOris** [comment]
i long press and it disabled like usual. so i dunno what you mean.

**Comment by ltguillaume** [comment]
Don't long-press the switch, long-press anywhere else on the item.

**Comment by TristisOris** [comment]
oh got it. that super ultra not obvious)
